#!/bin/bash

#
# hardhat_deploy
#
# Adds parameter support to the "hardhat deploy" command by creating environment variables with each arg.
# Environment variables are accessible through "process.env" in Hardhat scripts.
#

HH_CMD="npx hardhat"
HH_ARG_PREFIX="ARG_"

# -----------------------

function usage
{
	echo "hardhat_deploy [GLOBAL OPTIONS] deploy [DEPLOY ARGS] args [...]"
}

# -----------------------

arg_array=( "$@" )
arg_count=${#arg_array[@]}
user_arg_start=-1

# Find user arg starting position
i=0
for arg in "${arg_array[@]}"; do
	if [ "$arg" == "args" ]; then
		user_arg_start=$i
	fi
	((i++))
done

if [ $user_arg_start -lt 1 ]; then
	# user args not defined
	usage
	exit 1
fi

# Set env vars
i=0
for arg in "${arg_array[@]}"; do
	if [ $i -gt $user_arg_start ]; then
		j=$i
		((j -= user_arg_start))
		((j--))
		hh_arg="$HH_ARG_PREFIX$j"
		declare -x $hh_arg=$arg
	fi
	((i++))
done

# Generate command
cmd="$HH_CMD "

i=0
for arg in "${arg_array[@]}"; do
	if [ $i -lt $user_arg_start ]; then
		cmd="$cmd $arg"
	fi
	((i++))
done

# Run Hardhat
#echo $cmd
$cmd
hh_result=$?

# Clear env vars
i=0
for arg in "${arg_array[@]}"; do
	if [ $i -gt $user_arg_start ]; then
		j=$i
		((j -= user_arg_start))
		((j--))
		hh_arg="$HH_ARG_PREFIX$j"
		declare -x $hh_arg=""
	fi
	((i++))
done

exit $hh_result

# -----------------------

